[project]
name = "youtube-ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.8",
    "langchain-chroma>=1.1.0",
    "langchain-ollama>=1.0.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
]
